---
title: "Motor Trend Analysis"
author: "Tianxiang(Ivan) Liu"
date: "16 September 2014"
output: html_document
---

### Section 1. Executive Summary


---

### Section 2. Exploratory Analysis

```{r message=FALSE, warning=FALSE, fig.width=6, fig.align='center', fig.height=3, echo=TRUE, error=FALSE}

```

---

### Section 3. Model Selection

```{r message=FALSE, warning=FALSE, fig.width=6, fig.align='center', fig.height=3, echo=TRUE, error=FALSE}

```

---

### Section 4. Interpret Coefficient

```{r message=FALSE, warning=FALSE, fig.width=6, fig.align='center', fig.height=3, echo=TRUE, error=FALSE}

```

---

### Section 5. Diagonosis (Residual)

```{r message=FALSE, warning=FALSE, fig.width=6, fig.align='center', fig.height=3, echo=TRUE, error=FALSE}

```

---

### Section 6. Uncertency Inference

```{r message=FALSE, warning=FALSE, fig.width=6, fig.align='center', fig.height=3, echo=TRUE, error=FALSE}

```

---

### Section 7. Conclusion

```{r message=FALSE, warning=FALSE, fig.width=6, fig.align='center', fig.height=3, echo=TRUE, error=FALSE}

```

---